/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LabourRole;

import business.ecosystem.Ecosystem;
import business.enterprise.Enterprise;
import business.organization.LabourOrganization;
import business.organization.Organization;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Harsh
 */
public class LabourWorkAreaManangementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabourWorkAreaManangementJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private LabourOrganization organization;
    private UserAccount userAccount;
    private Ecosystem business;

    public LabourWorkAreaManangementJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = (LabourOrganization) organization;
        this.userAccount = account;
        this.business = business;

        valueLabel.setText(enterprise.getName());
        orgValueLabel.setText(organization.getName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customizedOrderJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        orgValueLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        inventoryWorkJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customizedOrderJButton.setBackground(new java.awt.Color(204, 204, 255));
        customizedOrderJButton.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        customizedOrderJButton.setText("Self Designed Orders Work Request");
        customizedOrderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customizedOrderJButtonActionPerformed(evt);
            }
        });
        add(customizedOrderJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 460, 140));

        backJButton.setBackground(new java.awt.Color(204, 204, 255));
        backJButton.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 40));

        enterpriseLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 110, 30));

        enterpriseLabel1.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Organization:");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 26));

        orgValueLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        orgValueLabel.setText("<value>");
        add(orgValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 87, 26));

        valueLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 90, 26));

        inventoryWorkJButton.setBackground(new java.awt.Color(204, 204, 255));
        inventoryWorkJButton.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        inventoryWorkJButton.setText("Inventory Work Requests");
        inventoryWorkJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryWorkJButtonActionPerformed(evt);
            }
        });
        add(inventoryWorkJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 350, 140));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Labourer Work Area Management");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void customizedOrderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customizedOrderJButtonActionPerformed
        // TODO add your handling code here:
        LabourWorkRequestsJPanel manufactureJPanel = new LabourWorkRequestsJPanel(userProcessContainer, userAccount, organization, enterprise, business);
        userProcessContainer.add("manufactureJPanel", manufactureJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_customizedOrderJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void inventoryWorkJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryWorkJButtonActionPerformed
        RequestsFromInventoryWorkRequestJPanel manufactureJPanel = new RequestsFromInventoryWorkRequestJPanel(userProcessContainer, userAccount, organization, enterprise, business);
        userProcessContainer.add("manufactureJPanelNew", manufactureJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_inventoryWorkJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton customizedOrderJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JButton inventoryWorkJButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel orgValueLabel;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
