/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LabourRole;

import business.ecosystem.Ecosystem;
import business.enterprise.CustomerSupportEnterprise;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.LabourOrganization;
import business.organization.Organization;
import business.organization.RealtorOrganization;
import business.useraccount.UserAccount;
import business.workqueue.SelfDesignedWorkRequest;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harsh
 */
public class LabourWorkRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabourWorkRequestsJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private LabourOrganization organization;
    private UserAccount userAccount;
    private Ecosystem business;

    public LabourWorkRequestsJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = (LabourOrganization) organization;
        this.userAccount = userAccount;
        this.business = business;

        populateDesignerWorkRequestTable();

        //add enterprise and organization name to label
        valueLabel.setText(enterprise.getName());
        orgValueLabel.setText(organization.getName());
    }

    public void populateDesignerWorkRequestTable() {
        DefaultTableModel model = (DefaultTableModel) designerWorkRequestJTable.getModel();

        model.setRowCount(0);

        for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof SelfDesignedWorkRequest) {
                Object[] row = new Object[5];
                SelfDesignedWorkRequest sdwr = (SelfDesignedWorkRequest) wr;
                row[0] = sdwr;
                row[1] = sdwr.getDesignerSender() == null ? null : sdwr.getDesignerSender().getEmployee().getName();
                row[2] = sdwr.getLabourerReceiver() == null ? null : sdwr.getLabourerReceiver().getEmployee().getName();
                row[3] = sdwr.getRequestDate();
                row[4] = sdwr.getStatus();
                model.addRow(row);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshTestJButton = new javax.swing.JButton();
        apartmentFurnishedJButton = new javax.swing.JButton();
        requestInventoryJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        designerWorkRequestJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        orgValueLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        acceptReqJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        refreshTestJButton.setBackground(new java.awt.Color(204, 204, 255));
        refreshTestJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });
        add(refreshTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 200, 180, 59));

        apartmentFurnishedJButton.setBackground(new java.awt.Color(204, 204, 255));
        apartmentFurnishedJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        apartmentFurnishedJButton.setText("Mark Apartment Furnished for Realtor");
        apartmentFurnishedJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apartmentFurnishedJButtonActionPerformed(evt);
            }
        });
        add(apartmentFurnishedJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 630, 400, 49));

        requestInventoryJButton.setBackground(new java.awt.Color(204, 204, 255));
        requestInventoryJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        requestInventoryJButton.setText("Request Inventory");
        requestInventoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestInventoryJButtonActionPerformed(evt);
            }
        });
        add(requestInventoryJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, 240, 47));

        designerWorkRequestJTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        designerWorkRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID", "Sender", "Receiver", "RequestDate", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(designerWorkRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 850, 290));

        backJButton.setBackground(new java.awt.Color(204, 204, 255));
        backJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, 60));

        jLabel2.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        jLabel2.setText("Architect's Work Queue");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 280, 50));

        enterpriseLabel1.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Organization:");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 26));

        enterpriseLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 110, 18));

        orgValueLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        orgValueLabel.setText("<value>");
        add(orgValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 220, 26));

        valueLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 220, 26));

        acceptReqJButton.setBackground(new java.awt.Color(204, 204, 255));
        acceptReqJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        acceptReqJButton.setText("Accept Request");
        acceptReqJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptReqJButtonActionPerformed(evt);
            }
        });
        add(acceptReqJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 570, -1, 49));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Labour Staff Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateDesignerWorkRequestTable();

    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void apartmentFurnishedJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apartmentFurnishedJButtonActionPerformed
        // TODO add your handling code here:

        int selectedRow = designerWorkRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first ", "Warning", JOptionPane.WARNING_MESSAGE);

            return;
        }

        SelfDesignedWorkRequest request = (SelfDesignedWorkRequest) designerWorkRequestJTable.getValueAt(selectedRow, 0);
        request.setStatus("Constructed");
        request.setLabourerSender(userAccount);
        request.setRealtorReceiver(null);
        userAccount.getWorkQueue().getWorkRequestList().add(request);
      
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof CustomerSupportEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof RealtorOrganization) {
                            
                            organization.getWorkQueue().getWorkRequestList().add(request);

                        }
                    }

                }
            }
        }
        populateDesignerWorkRequestTable();

        JOptionPane.showMessageDialog(null, "Apartment ready for move-in", "Info", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_apartmentFurnishedJButtonActionPerformed

    private void requestInventoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestInventoryJButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestInventoryJPanel", new InventoryRequestsJPanel(userProcessContainer, userAccount, enterprise, organization));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestInventoryJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void acceptReqJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptReqJButtonActionPerformed
        int selectedRow = designerWorkRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first ", "Warning", JOptionPane.WARNING_MESSAGE);

            return;
        }

        SelfDesignedWorkRequest request = (SelfDesignedWorkRequest) designerWorkRequestJTable.getValueAt(selectedRow, 0);

        request.setLabourerReceiver(userAccount);
        request.setStatus("Pending");

        populateDesignerWorkRequestTable();

        // TODO add your handling code here:
    }//GEN-LAST:event_acceptReqJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptReqJButton;
    private javax.swing.JButton apartmentFurnishedJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTable designerWorkRequestJTable;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel orgValueLabel;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JButton requestInventoryJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
