/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.reporting;

import business.ecosystem.Ecosystem;
import business.enterprise.UnitedConstructionEnterprise;
import business.enterprise.Enterprise;
import business.enterprise.RegulatoryEnterprise;
import business.network.Network;
import business.organization.Organization;
import business.organization.EnergyRegulatoryCommissionOrganization;
import business.organization.ReportingOrganization;
import business.useraccount.UserAccount;
import business.workqueue.BuyFurnishedApartmentWorkRequest;
import business.workqueue.RegulatoryWorkRequest;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.util.logging.*;

/**
 *
 * @author Harsh
 */
public class RegulatoryWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegulatoryWorkRequestJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private Ecosystem business;
    private Organization organization;
    private final static Logger logr = Logger.getLogger(Logger.GLOBAL_LOGGER_NAME);

    
    public RegulatoryWorkRequestJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = (ReportingOrganization) organization;
        this.account = account;
        this.enterprise = (UnitedConstructionEnterprise) enterprise;
        this.business = business;

        valueLabel.setText(enterprise.getName());
        orgValueLabel.setText(organization.getName());
       
        populateRegulatoryTable();
    }

    public void populateRegulatoryTable() {
        DefaultTableModel model = (DefaultTableModel) regulatoryWorkRequestJTable.getModel();

        model.setRowCount(0);
        {
            for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
                if (wr instanceof RegulatoryWorkRequest) {
                    Object[] row = new Object[5];
                    RegulatoryWorkRequest rwr = (RegulatoryWorkRequest) wr;
                    row[0] = rwr;
                    row[1] = rwr.getSender().getEmployee().getName();
                    row[2] = rwr.getReceiver() == null ? null : rwr.getReceiver().getEmployee().getName();
                    row[3] = rwr.getRequestDate();
                    row[4] = rwr.getStatus();
                    model.addRow(row);

                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        regulatoryWorkRequestJTable = new javax.swing.JTable();
        enterpriseLabel = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        orgValueLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        refreshJButton = new javax.swing.JButton();
        sendToRegulatoryJButton = new javax.swing.JButton();
        acceptReqJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton7.setBackground(new java.awt.Color(204, 204, 255));
        backJButton7.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        backJButton7.setForeground(new java.awt.Color(51, 51, 51));
        backJButton7.setText("Back");
        backJButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton7ActionPerformed(evt);
            }
        });
        add(backJButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 50));

        regulatoryWorkRequestJTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        regulatoryWorkRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "RequestType", "Sender", "Receiver", "RequestDate", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(regulatoryWorkRequestJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 900, 140));

        enterpriseLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, 30));

        enterpriseLabel1.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Organization:");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 26));

        orgValueLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        orgValueLabel.setText("<value>");
        add(orgValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 106, 26));

        valueLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 106, 26));

        refreshJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 340, 180, 40));

        sendToRegulatoryJButton.setBackground(new java.awt.Color(204, 204, 255));
        sendToRegulatoryJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        sendToRegulatoryJButton.setText("Send Report to Regulatory");
        sendToRegulatoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendToRegulatoryJButtonActionPerformed(evt);
            }
        });
        add(sendToRegulatoryJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 630, 270, 43));

        acceptReqJButton.setBackground(new java.awt.Color(204, 204, 255));
        acceptReqJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        acceptReqJButton.setText("Accept Request");
        acceptReqJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptReqJButtonActionPerformed(evt);
            }
        });
        add(acceptReqJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 270, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Reporting Staff Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 24)); // NOI18N
        jLabel2.setText("Regulatory Work Requests");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 330, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton7ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton7ActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateRegulatoryTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void sendToRegulatoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendToRegulatoryJButtonActionPerformed

        int selectedRow = regulatoryWorkRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first ", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        //sending regulatory work request to regulatory with report
        RegulatoryWorkRequest request = (RegulatoryWorkRequest) regulatoryWorkRequestJTable.getValueAt(selectedRow, 0);

        request.setStatus("Report Sent");

        account.getWorkQueue().getWorkRequestList().add(request);

        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof RegulatoryEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof EnergyRegulatoryCommissionOrganization) {
                            organization.getWorkQueue().getWorkRequestList().add(request);
                        }
                    }
                }
            }
        }

        JOptionPane.showMessageDialog(null, "Report sent to Energy Regulatory Commission", "Info", JOptionPane.INFORMATION_MESSAGE);

        populateRegulatoryTable();
        logr.info("Send Report to Regulatory Button clicked");
    }//GEN-LAST:event_sendToRegulatoryJButtonActionPerformed

    private void acceptReqJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptReqJButtonActionPerformed
        int selectedRow = regulatoryWorkRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first ", "Warning", JOptionPane.WARNING_MESSAGE);

            return;
        }

        RegulatoryWorkRequest request = (RegulatoryWorkRequest) regulatoryWorkRequestJTable.getValueAt(selectedRow, 0);
        request.setReceiver(account);
        request.setStatus("Pending");

        populateRegulatoryTable();
        logr.info("Accept Request Button clicked");
        // TODO add your handling code here:
    }//GEN-LAST:event_acceptReqJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptReqJButton;
    private javax.swing.JButton backJButton7;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel orgValueLabel;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JTable regulatoryWorkRequestJTable;
    private javax.swing.JButton sendToRegulatoryJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
