/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.reporting;


import Business.Customer.SelfDesignedOrder;
import Business.Customer.SelfDesignedOrderItem;
import Business.Customer.MasterOrderList;
import Business.Customer.BuyFurnishedApartment;
import business.ecosystem.Ecosystem;
import business.enterprise.Enterprise;
import business.organization.Organization;
import business.organization.ReportingOrganization;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import java.util.logging.*;


/**
 *
 * @author Harsh
 */
public class ReportingWorkAreaManagementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportingWorkAreaManagementJPanel
     */
    private MasterOrderList mod;
    private SelfDesignedOrder customizedOrder;
    private SelfDesignedOrderItem customizedOrderItem;
    private BuyFurnishedApartment orderFurnishedApt;
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private Ecosystem business;
    private Organization organization;

    final String applicationTitle = "Energy Savings";
    final String chartTitle = "Energy Savings";
    private final static Logger logr = Logger.getLogger(Logger.GLOBAL_LOGGER_NAME);


    public ReportingWorkAreaManagementJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = (ReportingOrganization) organization;
        this.account = account;
        this.enterprise = enterprise;
        this.business = business;

        valueLabel.setText(enterprise.getName());
        orgValueLabel.setText(organization.getName());
        logr.info("Entered the Reporting UI");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        energySavingsjBtn = new javax.swing.JButton();
        revenueJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        orgValueLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        workRequestJButton = new javax.swing.JButton();
        orgSizejButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setBackground(new java.awt.Color(204, 204, 255));
        backJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 80, 50));

        energySavingsjBtn.setBackground(new java.awt.Color(204, 204, 255));
        energySavingsjBtn.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 18)); // NOI18N
        energySavingsjBtn.setText("Apartment Energy Savings");
        energySavingsjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                energySavingsjBtnActionPerformed(evt);
            }
        });
        add(energySavingsjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 280, 80));

        revenueJButton.setBackground(new java.awt.Color(204, 204, 255));
        revenueJButton.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 18)); // NOI18N
        revenueJButton.setText("Revenue Estimates");
        revenueJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revenueJButtonActionPerformed(evt);
            }
        });
        add(revenueJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 370, 210, 80));

        enterpriseLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        enterpriseLabel1.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Organization:");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        orgValueLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        orgValueLabel.setText("<value>");
        add(orgValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 190, -1));

        valueLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 230, -1));

        workRequestJButton.setBackground(new java.awt.Color(204, 204, 255));
        workRequestJButton.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 18)); // NOI18N
        workRequestJButton.setText("Work Requests");
        workRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workRequestJButtonActionPerformed(evt);
            }
        });
        add(workRequestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 260, 80));

        orgSizejButton.setBackground(new java.awt.Color(204, 204, 255));
        orgSizejButton.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 18)); // NOI18N
        orgSizejButton.setText("Organization Size");
        orgSizejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgSizejButtonActionPerformed(evt);
            }
        });
        add(orgSizejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 270, 80));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Reporting Work Area Management");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/report.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButtonActionPerformed

    private void energySavingsjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_energySavingsjBtnActionPerformed
        // TODO add your handling code here:

        EnergyContentReportJPanel lcjp = new EnergyContentReportJPanel(userProcessContainer, mod,business);
        userProcessContainer.add("EnergyContentReportJPanel", lcjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        logr.info("Apartment Energy Savings Button clicked");
    }//GEN-LAST:event_energySavingsjBtnActionPerformed

    private void workRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workRequestJButtonActionPerformed
       
        RegulatoryWorkRequestJPanel ojp = new RegulatoryWorkRequestJPanel(userProcessContainer,account,organization,enterprise, business);
        userProcessContainer.add("RegulatoryWorkRequests", ojp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        logr.info("Work Requests Button clicked");
    }//GEN-LAST:event_workRequestJButtonActionPerformed

    private void orgSizejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgSizejButtonActionPerformed
         OrganisationReportJPanel ojp = new OrganisationReportJPanel(userProcessContainer, mod, business);
        userProcessContainer.add("OrganizationReportJPanel", ojp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        logr.info("Organization Size Button clicked");
    }//GEN-LAST:event_orgSizejButtonActionPerformed

    private void revenueJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revenueJButtonActionPerformed
        // TODO add your handling code here:
        RevenueReportJPanel rrjp = new RevenueReportJPanel(userProcessContainer, mod, business);
        userProcessContainer.add("EnergyContentReportJPanel", rrjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        logr.info("Revenue Estimates Button clicked");
        //            JOptionPane.showMessageDialog(null, customizedRevenue, "Warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_revenueJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton energySavingsjBtn;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton orgSizejButton;
    private javax.swing.JLabel orgValueLabel;
    private javax.swing.JButton revenueJButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JButton workRequestJButton;
    // End of variables declaration//GEN-END:variables
}
