/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EnergyRegulatoryCommission;

import business.ecosystem.Ecosystem;
import business.enterprise.UnitedConstructionEnterprise;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.Organization;
import business.organization.EnergyRegulatoryCommissionOrganization;
import business.organization.ReportingOrganization;
import business.useraccount.UserAccount;
import business.workqueue.RegulatoryWorkRequest;
import java.awt.CardLayout;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.logging.*;

/**
 *
 * @author Harsh
 */
public class EnergyRegulatoryCommissionWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Organization organization;
    private UserAccount userAccount;
    private Ecosystem business;
    private final static Logger logr = Logger.getLogger(Logger.GLOBAL_LOGGER_NAME);


    /**
     * Creates new form EnergyRegulatoryCommissionWorkAreaJPanel
     */
    public EnergyRegulatoryCommissionWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = (EnergyRegulatoryCommissionOrganization) organization;
        this.userAccount = account;
        this.business = business;

        valueLabel.setText(enterprise.getName());
        orgValueLabel.setText(organization.getName());
        logr.info("Entered the Energy Regulatory Commision UI");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genReportjButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        orgValueLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        requestReportJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        genReportjButton.setBackground(new java.awt.Color(204, 204, 255));
        genReportjButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        genReportjButton.setText("Fetch Energy Reports");
        genReportjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genReportjButtonActionPerformed(evt);
            }
        });
        add(genReportjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 390, 90));

        backJButton.setBackground(new java.awt.Color(204, 204, 255));
        backJButton.setFont(new java.awt.Font("Palatino", 0, 24)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 110, 40));

        enterpriseLabel.setFont(new java.awt.Font("Palatino", 0, 24)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 127, 40));

        enterpriseLabel1.setFont(new java.awt.Font("Palatino", 0, 24)); // NOI18N
        enterpriseLabel1.setText("Organization:");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 26));

        orgValueLabel.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        orgValueLabel.setText("<value>");
        add(orgValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 330, 30));

        valueLabel.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 300, 40));

        requestReportJButton.setBackground(new java.awt.Color(204, 204, 255));
        requestReportJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        requestReportJButton.setText("Request Report");
        requestReportJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestReportJButtonActionPerformed(evt);
            }
        });
        add(requestReportJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 390, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/quality control.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 510, 510));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Energy Regulatory Commission Staff Work Area");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void genReportjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genReportjButtonActionPerformed
        //reports generated with the regulatory
        File file = new File("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\UnitedConstructionProject\\src\\userinterface\\EnergyRegulatoryCommission\\ReportProcess.csv");
        float energySaving = 0;
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof UnitedConstructionEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof ReportingOrganization) {

                            energySaving = ((ReportingOrganization) organization).getReport().getTotalEnergySaving();

                        }
                    }
                }
            }
        }

        String content = "The Energy Savings Reports is as follows:" + "    " +"The cumulative Energy Savings is:" + " " + energySaving + "%";

        try (FileOutputStream fop = new FileOutputStream(file)) {

            // Create new file if file dosen't exist
            if (!file.exists()) {
                file.createNewFile();
            }

            // Get file content in bytes
            byte[] contentInBytes = content.getBytes();

            fop.write(contentInBytes);
            fop.flush(); //write the content of the buffer to the file
            fop.close(); //closes the stream permanently

        } catch (IOException e) {
            e.printStackTrace(); //prints the throwable
        }

        JOptionPane.showMessageDialog(null, "Report fetched and saved sucesfully", "Info", JOptionPane.INFORMATION_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_genReportjButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void requestReportJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestReportJButtonActionPerformed
         //request sent to regulatory
        RegulatoryWorkRequest rwr = new RegulatoryWorkRequest();
        rwr.setStatus("Report Requested");
        rwr.setSender(userAccount);
        String reportType = "Energy Savings";
        rwr.setReportType(reportType);
       //adding work request to the reporting organization work queue
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof UnitedConstructionEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof ReportingOrganization) {
                            organization.getWorkQueue().getWorkRequestList().add(rwr);
                        }
                    }
                }
            }
        }

        JOptionPane.showMessageDialog(null, "Report requested from Reporting Organisation", "Info", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_requestReportJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JButton genReportjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel orgValueLabel;
    private javax.swing.JButton requestReportJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
