/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ArchitectRole;

import business.ecosystem.Ecosystem;
import business.enterprise.Enterprise;
import business.organization.LayoutOrganization;
import business.organization.LabourOrganization;
import business.organization.Organization;
import business.useraccount.UserAccount;
import business.workqueue.SelfDesignedWorkRequest;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harsh
 */
public class ArchitectWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form designWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private LayoutOrganization designOrganization;
    private UserAccount userAccount;
    private Ecosystem business;

    public ArchitectWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.designOrganization = (LayoutOrganization) organization;
        this.userAccount = userAccount;
        this.business = business;

        populateDesignTable();
        //add enterprise name to label
        valueLabel.setText(enterprise.getName());
        orgValueLabel.setText(organization.getName());
    }

    public void populateDesignTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);

        for (WorkRequest wr : designOrganization.getWorkQueue().getWorkRequestList()) {

            Object[] row = new Object[5];
            SelfDesignedWorkRequest sdwr = (SelfDesignedWorkRequest) wr;
            row[0] = sdwr;
            row[1] = sdwr.getRealtorSender() == null ? null : sdwr.getRealtorSender().getEmployee().getName();
            row[2] = sdwr.getDesignerReceiver() == null ? null : sdwr.getDesignerReceiver().getEmployee().getName();
            row[3] = sdwr.getRequestDate();
            row[4] = sdwr.getStatus();
            model.addRow(row);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshTestJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        requestLabourertJButton = new javax.swing.JButton();
        designCompleteJButton = new javax.swing.JButton();
        acceptRequestJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        orgValueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        refreshTestJButton.setBackground(new java.awt.Color(204, 204, 255));
        refreshTestJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });
        add(refreshTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 220, 190, 40));

        workRequestJTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID", "Sender", "Receiver", "RequestDate", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 930, 270));

        requestLabourertJButton.setBackground(new java.awt.Color(204, 204, 255));
        requestLabourertJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        requestLabourertJButton.setText("Request Labour Team");
        requestLabourertJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestLabourertJButtonActionPerformed(evt);
            }
        });
        add(requestLabourertJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 720, 230, 49));

        designCompleteJButton.setBackground(new java.awt.Color(204, 204, 255));
        designCompleteJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        designCompleteJButton.setText("Design Complete");
        designCompleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designCompleteJButtonActionPerformed(evt);
            }
        });
        add(designCompleteJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 640, 230, 49));

        acceptRequestJButton.setBackground(new java.awt.Color(204, 204, 255));
        acceptRequestJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        acceptRequestJButton.setText("Accept Request");
        acceptRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptRequestJButtonActionPerformed(evt);
            }
        });
        add(acceptRequestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 230, 48));

        backJButton.setBackground(new java.awt.Color(204, 204, 255));
        backJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 40));

        valueLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 300, 20));

        enterpriseLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, 30));

        enterpriseLabel1.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Organization:");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 26));

        orgValueLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        orgValueLabel.setText("<value>");
        add(orgValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 290, 26));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Layout Staff Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateDesignTable();

    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void requestLabourertJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestLabourertJButtonActionPerformed
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);

            return;
        }

        SelfDesignedWorkRequest cRequest = (SelfDesignedWorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
        //check the status for designer
        if (cRequest.getStatus().equals("Order Ready")) {
            JOptionPane.showMessageDialog(null, "Please complete the design first", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (cRequest.getStatus().equals("Pending With Design")) {
            JOptionPane.showMessageDialog(null, "The design is not ready", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (cRequest.getStatus().equals("Design Complete")) {
            cRequest.setStatus("Manufacture Order");
            cRequest.setDesignerSender(userAccount);
            userAccount.getWorkQueue().getWorkRequestList().add(cRequest);

            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof LabourOrganization) {
                    organization.getWorkQueue().getWorkRequestList().add(cRequest);

                }

            }
            JOptionPane.showMessageDialog(null, " Design sent to Labourer for manufacturing", "Warning", JOptionPane.WARNING_MESSAGE);

        }


    }//GEN-LAST:event_requestLabourertJButtonActionPerformed

    private void acceptRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptRequestJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);

            return;
        }

        SelfDesignedWorkRequest request = (SelfDesignedWorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
        request.setDesignerReceiver(userAccount);
        request.setStatus("Pending With Design");
        populateDesignTable();
    }//GEN-LAST:event_acceptRequestJButtonActionPerformed

    private void designCompleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designCompleteJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);

            return;
        }

        SelfDesignedWorkRequest request = (SelfDesignedWorkRequest) workRequestJTable.getValueAt(selectedRow, 0);

        request.setStatus("Design Complete");
        populateDesignTable();


    }//GEN-LAST:event_designCompleteJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptRequestJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton designCompleteJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel orgValueLabel;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JButton requestLabourertJButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
