/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.customer;

import Business.Customer.ApartmentOrderItem;
import Business.Customer.RealtorApartment;
import Business.Customer.ApartmentCatalog;
import Business.Customer.MasterOrderList;
import Business.Customer.BuyFurnishedApartment;
import business.ecosystem.Ecosystem;
import business.enterprise.CustomerSupportEnterprise;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.CustomerOrganization;
import business.organization.Organization;
import business.organization.RealtorOrganization;
import business.useraccount.UserAccount;
import business.workqueue.BuyFurnishedApartmentWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harsh
 */
public class BuyFurnishedApartmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BuyFurnishedAptJPanelNew
     */
    private JPanel userProcessContainer;
    private MasterOrderList mod;
    private CustomerOrganization customerOrganization;
    private UserAccount account;
    private Enterprise enterprise;
    private Ecosystem business;

    public BuyFurnishedApartmentJPanel(JPanel userProcessContainer, Organization organization, UserAccount account, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customerOrganization = (CustomerOrganization) organization;
        this.account = account;
        this.enterprise = enterprise;
        this.business = business;

        populateTable();

    }
    BuyFurnishedApartment bfa = new BuyFurnishedApartment();
    ApartmentOrderItem aoi = new ApartmentOrderItem();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        RealtorApartmentsJTable = new javax.swing.JTable();
        placeOrderJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton2.setBackground(new java.awt.Color(204, 204, 255));
        backJButton2.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        backJButton2.setText("Back");
        backJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton2ActionPerformed(evt);
            }
        });
        add(backJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 140, 50));

        RealtorApartmentsJTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        RealtorApartmentsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RealtorApartmentId", "ApartmentType", "HosuingComplex", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(RealtorApartmentsJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 850, 340));

        placeOrderJButton.setBackground(new java.awt.Color(204, 204, 255));
        placeOrderJButton.setFont(new java.awt.Font("Palatino", 1, 14)); // NOI18N
        placeOrderJButton.setText("Place Order");
        placeOrderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderJButtonActionPerformed(evt);
            }
        });
        add(placeOrderJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 650, 240, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/furnished apartment.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("BUY FURNISHED APARTMENT");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
   private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) RealtorApartmentsJTable.getModel();
        dtm.setRowCount(0);
        for (Organization realtorOrganization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (realtorOrganization instanceof RealtorOrganization) {
                ApartmentCatalog aptCatalogat = ((RealtorOrganization) realtorOrganization).getAptCatalog();

                for (RealtorApartment apt : aptCatalogat.getListOfRealtorApartments()) {
                    Object[] row = new Object[4];
                    row[0] = apt;
                    row[1] = apt.getApartmentType();
                    row[2] = apt.getHousingComplexType();
                    row[3] = apt.getPrice();
                    dtm.addRow(row);
                }
            }
        }
    }


    private void backJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton2ActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton2ActionPerformed

    private void placeOrderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderJButtonActionPerformed
        int selectedRow = RealtorApartmentsJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        RealtorApartment apt = (RealtorApartment) RealtorApartmentsJTable.getValueAt(selectedRow, 0);
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof CustomerSupportEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof RealtorOrganization) {
                            mod = ((RealtorOrganization) organization).getMod();
                        }

                    }
                }
            }
        }
        aoi = bfa.addApartmentOrderItem();
        aoi.setRealtorApartment(apt);
        bfa.setCustomer(account.getEmployee());

        mod.addRealtorOrder(bfa);

        BuyFurnishedApartmentWorkRequest orderFurnishedAptWR = new BuyFurnishedApartmentWorkRequest();
        orderFurnishedAptWR.setOrderFurnishedApt(bfa);
        orderFurnishedAptWR.setStatus("Placed");
        orderFurnishedAptWR.setSender(account);
        account.getWorkQueue().getWorkRequestList().add(orderFurnishedAptWR);

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof RealtorOrganization) {
                organization.getWorkQueue().getWorkRequestList().add(orderFurnishedAptWR);
            }
        }

        JOptionPane.showMessageDialog(null, "Order Placed Successfully", "Information!!", JOptionPane.WARNING_MESSAGE);


    }//GEN-LAST:event_placeOrderJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RealtorApartmentsJTable;
    private javax.swing.JButton backJButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton placeOrderJButton;
    // End of variables declaration//GEN-END:variables
}
