/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.customer;

import business.ecosystem.Ecosystem;
import business.enterprise.Enterprise;
import business.organization.CustomerOrganization;
import business.organization.Organization;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import java.util.logging.*;

/**
 *
 * @author Harsh
 */
public class CustomerMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private JPanel userProcessContainer;
    private CustomerOrganization customerOrganization;
    private UserAccount account;
    private Enterprise enterprise;
    private Ecosystem business;
    private final static Logger logr = Logger.getLogger(Logger.GLOBAL_LOGGER_NAME);

    public CustomerMainJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customerOrganization = (CustomerOrganization) organization;
        this.account = account;
        this.enterprise = enterprise;
        this.business = business;
        customerTextField.setText(account.getUsername());
        logr.info("Entered the Customer UI");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customizejBtn = new javax.swing.JButton();
        buyFurnishedAptjBtn = new javax.swing.JButton();
        customerOrdersJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        customerTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customizejBtn.setBackground(new java.awt.Color(204, 204, 255));
        customizejBtn.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        customizejBtn.setText("Design your Apartment");
        customizejBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customizejBtnActionPerformed(evt);
            }
        });
        add(customizejBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 270, 120));

        buyFurnishedAptjBtn.setBackground(new java.awt.Color(204, 204, 255));
        buyFurnishedAptjBtn.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        buyFurnishedAptjBtn.setText("Buy Furnished Apartment");
        buyFurnishedAptjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyFurnishedAptjBtnActionPerformed(evt);
            }
        });
        add(buyFurnishedAptjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 270, 120));

        customerOrdersJButton.setBackground(new java.awt.Color(204, 204, 255));
        customerOrdersJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        customerOrdersJButton.setText("Requested Order");
        customerOrdersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerOrdersJButtonActionPerformed(evt);
            }
        });
        add(customerOrdersJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, 270, 120));

        backJButton.setBackground(new java.awt.Color(204, 204, 255));
        backJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, 50));

        customerTextField.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        customerTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        customerTextField.setEnabled(false);
        customerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerTextFieldActionPerformed(evt);
            }
        });
        add(customerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 120, 30));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("WELCOME CUSTOMER");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customer.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 230, 420, 290));

        jLabel3.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel3.setText("Welcome:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    private void customizejBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customizejBtnActionPerformed

        // TODO add your handling code here:
        CustomizeJPanel cjp = new CustomizeJPanel(userProcessContainer, customerOrganization, account, enterprise, business);
        userProcessContainer.add("CustomizeJPanel", cjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_customizejBtnActionPerformed

    private void buyFurnishedAptjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyFurnishedAptjBtnActionPerformed
        //  TODO add your handling code here:
        //try {
            BuyFurnishedApartmentJPanel cjp = new BuyFurnishedApartmentJPanel(userProcessContainer, customerOrganization, account, enterprise, business);
            userProcessContainer.add("BuyFurnishedApartmentJPanel", cjp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        //} 
//        catch (java.lang.NullPointerException exception) {
//        // Catch NullPointerExceptions
//            System.out.println("");
//        }
//        catch (Throwable exception) {
//        // Catch other Throwables
//            System.out.println(exception);
//        }
    }//GEN-LAST:event_buyFurnishedAptjBtnActionPerformed

    private void customerOrdersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerOrdersJButtonActionPerformed
        //  TODO add your handling code here:
        CustomerOrdersJPanel cjp = new CustomerOrdersJPanel(userProcessContainer, account, customerOrganization, enterprise, business);
        userProcessContainer.add("CustomerOrdersJPanel", cjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_customerOrdersJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void customerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerTextFieldActionPerformed

    }//GEN-LAST:event_customerTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton buyFurnishedAptjBtn;
    private javax.swing.JButton customerOrdersJButton;
    private javax.swing.JTextField customerTextField;
    private javax.swing.JButton customizejBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
