/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.customer;

import Business.Customer.MasterOrderList;
import Business.Customer.SelfDesignedOrder;
import Business.Customer.SelfDesignedOrderItem;
import business.ecosystem.Ecosystem;
import business.enterprise.CustomerSupportEnterprise;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.CustomerOrganization;
import business.organization.Organization;
import business.organization.RealtorOrganization;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Harsh
 */
public class CustomizeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BuyFurnishedAptJPanel
     */
    private JPanel userProcessContainer;
    private MasterOrderList mod;
    private CustomerOrganization customerOrganization;
    private UserAccount account;
    private Enterprise enterprise;
    private Ecosystem business;
    private static int count;
    
    public CustomizeJPanel(JPanel userProcessContainer, Organization organization, UserAccount account, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customerOrganization = (CustomerOrganization) organization;
        this.account = account;
        this.enterprise = enterprise;
        this.business = business;
        customerTextField.setText(account.getUsername());
    }
    SelfDesignedOrder order = new SelfDesignedOrder();
    SelfDesignedOrderItem oi = new SelfDesignedOrderItem();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        spaceHeatingjComboBox = new javax.swing.JComboBox<>();
        apartmentTypejComboBox = new javax.swing.JComboBox();
        powerTypejComboBox = new javax.swing.JComboBox();
        windowjComboBox = new javax.swing.JComboBox<>();
        flooringjComboBox = new javax.swing.JComboBox<>();
        housingComplexTypejComboBox = new javax.swing.JComboBox<>();
        furnitureWoodjComboBox = new javax.swing.JComboBox<>();
        interiorThemeTypejComboBox = new javax.swing.JComboBox<>();
        lightFixtureTypejComboBox = new javax.swing.JComboBox<>();
        customerTextField = new javax.swing.JTextField();
        nextJButton = new javax.swing.JButton();
        addJBtn = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText(" DESIGN YOUR OWN APARTMENT");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jLabel2.setText("Apartment Type:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 90, 20));

        jLabel3.setText("Apartment Power Type:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, 30));

        jLabel4.setText("Windows:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 80, 40));

        jLabel5.setText("Flooring Type:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, -1, 20));

        jLabel6.setText("Space Heating System:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, 30));

        jLabel7.setText("Housing Complex:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, -1, 30));

        jLabel8.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel8.setText("Welcome:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jLabel9.setText("Furniture Wood:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, -1, 30));

        jLabel10.setText("Interior Type:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 590, -1, -1));

        jLabel11.setText("Light Fixturel Type:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customize.jpg"))); // NOI18N
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 270, -1, -1));

        spaceHeatingjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electricity", "Gas-Fired", "Wood-Burning", "Boiler" }));
        spaceHeatingjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spaceHeatingjComboBoxActionPerformed(evt);
            }
        });
        add(spaceHeatingjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 140, -1));

        apartmentTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Studio", "2BHK", "3BHK" }));
        apartmentTypejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apartmentTypejComboBoxActionPerformed(evt);
            }
        });
        add(apartmentTypejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 140, -1));

        powerTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Electricity", "Solar", "Hybrid energy" }));
        powerTypejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerTypejComboBoxActionPerformed(evt);
            }
        });
        add(powerTypejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 140, -1));

        windowjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single Glass", "Double Pane", "Low E4" }));
        windowjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowjComboBoxActionPerformed(evt);
            }
        });
        add(windowjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 140, 20));

        flooringjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wooden", "Marble", "Ceramic Tiles" }));
        flooringjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flooringjComboBoxActionPerformed(evt);
            }
        });
        add(flooringjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 140, -1));

        housingComplexTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avalon Residences", "Windsor at Oak Grove", "Burbank Apartments", "Church Park Luxury Apartments" }));
        housingComplexTypejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                housingComplexTypejComboBoxActionPerformed(evt);
            }
        });
        add(housingComplexTypejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 140, -1));

        furnitureWoodjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oak", "Maple", "Redwood" }));
        add(furnitureWoodjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 140, -1));

        interiorThemeTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vintage", "Modern", "Contemporary", "Bohemian" }));
        interiorThemeTypejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interiorThemeTypejComboBoxActionPerformed(evt);
            }
        });
        add(interiorThemeTypejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 590, 140, -1));

        lightFixtureTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LED", "CFL", "Incandescent Light Bulbs" }));
        lightFixtureTypejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightFixtureTypejComboBoxActionPerformed(evt);
            }
        });
        add(lightFixtureTypejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 140, -1));

        customerTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        customerTextField.setEnabled(false);
        customerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerTextFieldActionPerformed(evt);
            }
        });
        add(customerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 120, 30));

        nextJButton.setBackground(new java.awt.Color(204, 204, 255));
        nextJButton.setText("View Cart");
        nextJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextJButtonActionPerformed(evt);
            }
        });
        add(nextJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 690, 100, 50));

        addJBtn.setBackground(new java.awt.Color(204, 204, 255));
        addJBtn.setText("Add to Cart");
        addJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJBtnActionPerformed(evt);
            }
        });
        add(addJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 690, 120, 50));

        backJButton.setBackground(new java.awt.Color(204, 204, 255));
        backJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 110, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void nextJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextJButtonActionPerformed
        
        ManageOrderJPanel vjp = new ManageOrderJPanel(userProcessContainer, mod, order, customerOrganization, account, enterprise, business);
        userProcessContainer.add("ManageOrderJPanel", vjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_nextJButtonActionPerformed

    private void powerTypejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerTypejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_powerTypejComboBoxActionPerformed

    private void interiorThemeThemejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interiorThemeThemejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interiorThemeThemejComboBoxActionPerformed

    private void addJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJBtnActionPerformed
        
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof CustomerSupportEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof RealtorOrganization) {
                            mod = ((RealtorOrganization) organization).getMod();
                        }                        
                        
                    }
                }
            }
        }

        // add customised order item to the order
        count++;
        SelfDesignedOrderItem oi = order.addCustomizedOrderItem();
        order.setCustomer(account.getEmployee());
        order.setOrderNumber(count);
        
        float price = 0;
        oi.getCustomizeProduct().setApartmentType(apartmentTypejComboBox.getSelectedItem().toString());
        oi.getCustomizeProduct().setPowerType(powerTypejComboBox.getSelectedItem().toString());
        oi.getCustomizeProduct().setWindow(windowjComboBox.getSelectedItem().toString());
        oi.getCustomizeProduct().setFlooring(flooringjComboBox.getSelectedItem().toString());
        oi.getCustomizeProduct().setLightFixtureType(lightFixtureTypejComboBox.getSelectedItem().toString());
        oi.getCustomizeProduct().setHousingComplexType(housingComplexTypejComboBox.getSelectedItem().toString());
        oi.getCustomizeProduct().setSpaceHeating(spaceHeatingjComboBox.getSelectedItem().toString());
        oi.getCustomizeProduct().setInteriorThemeType(interiorThemeTypejComboBox.getSelectedItem().toString());
        oi.getCustomizeProduct().setFurnitureWoodType(furnitureWoodjComboBox.getSelectedItem().toString());
        
        

        //Light price
        if (oi.getCustomizeProduct().getLightFixtureType().equalsIgnoreCase("LED")) {
            price = price + 6500;
        } else if (oi.getCustomizeProduct().getLightFixtureType().equalsIgnoreCase("CFL")) {
            price = price + 1000;
            
        }  else if (oi.getCustomizeProduct().getLightFixtureType().equalsIgnoreCase("Incandescent Light Bulbs")) {
            price = price + 500;
            
        }
        
        //Power price
        if (oi.getCustomizeProduct().getPowerType().equalsIgnoreCase("Electricity")) {
            price = price + 4000;            
        } else if (oi.getCustomizeProduct().getPowerType().equalsIgnoreCase("Solar")) {
            price = price + 5500;            
        } else if (oi.getCustomizeProduct().getPowerType().equalsIgnoreCase("Hybrid energy")) {
            price = price + 7000;            
        }

        //Window price   
        if (oi.getCustomizeProduct().getWindow().equalsIgnoreCase("Single Glass")) {
            price = price + 4000;
        } else if (oi.getCustomizeProduct().getWindow().equalsIgnoreCase("Double Pane")) {
            price = price + 7000;
        } else if (oi.getCustomizeProduct().getWindow().equalsIgnoreCase("Low E4")) {
            price = price + 9000;
        }

        //Floor price
        if (oi.getCustomizeProduct().getFlooring().equalsIgnoreCase("Wooden")) {
            price = price + 5000;
        } else if (oi.getCustomizeProduct().getFlooring().equalsIgnoreCase("Marble")) {
            price = price + 9500;
        } else if (oi.getCustomizeProduct().getFlooring().equalsIgnoreCase("Ceramic Tiles")) {
            price = price + 3000;
        }

        //Space Heating price        
        if (oi.getCustomizeProduct().getSpaceHeating().equalsIgnoreCase("Electricity")) {
            price = price + 1500;
        } else if (oi.getCustomizeProduct().getSpaceHeating().equalsIgnoreCase("Gas-Fired")) {
            price = price + 4000;
        } else if (oi.getCustomizeProduct().getSpaceHeating().equalsIgnoreCase("Wood-Burning")) {
            price = price + 1900;
        } else if (oi.getCustomizeProduct().getSpaceHeating().equalsIgnoreCase("Boiler")) {
            price = price + 4000;         
        }
        
        //Housing Complex price
        if (oi.getCustomizeProduct().getHousingComplexType().equalsIgnoreCase("Avalon Residences")) {
            price = price + 1000;
        } else if (oi.getCustomizeProduct().getHousingComplexType().equalsIgnoreCase("Windsor at Oak Grove")) {
            price = price + 2000;
        } else if (oi.getCustomizeProduct().getHousingComplexType().equalsIgnoreCase("Burbank Apartments")) {
            price = price + 3000;
        } else if (oi.getCustomizeProduct().getHousingComplexType().equalsIgnoreCase("Church Park Luxury Apartments")) {
            price = price + 4000;
        }
        
        //Wood Furniture pricing
        if (oi.getCustomizeProduct().getFurnitureWoodType().equalsIgnoreCase("Oak")) {
            price = price + 5000;
        } else if (oi.getCustomizeProduct().getFurnitureWoodType().equalsIgnoreCase("Maple")) {
            price = price + 6000;
        } else if (oi.getCustomizeProduct().getFurnitureWoodType().equalsIgnoreCase("Redwood")) {
            price = price + 7000;
        }

        //Interior Theme pricing
        if (oi.getCustomizeProduct().getInteriorThemeType().equalsIgnoreCase("Vintage")) {
            price = price + 500;
        } else if (oi.getCustomizeProduct().getInteriorThemeType().equalsIgnoreCase("Modern")) {
            price = price + 800;
        } else if (oi.getCustomizeProduct().getInteriorThemeType().equalsIgnoreCase("Contemporary")) {
            price = price + 1000;
        } else if (oi.getCustomizeProduct().getInteriorThemeType().equalsIgnoreCase("Bohemian")) {
            price = price + 1200;
        }
        
        //Apartment Type pricing
        if (oi.getCustomizeProduct().getApartmentType().equalsIgnoreCase("Studio")) {
            price = price + 200000;
        } else if (oi.getCustomizeProduct().getApartmentType().equalsIgnoreCase("2BHK")) {
            price = 2 * price + 500000;
        } else {
            price = 3 * price + 700000;
        }
        
        oi.getCustomizeProduct().setPrice(price);
        JOptionPane.showMessageDialog(null, "Your house customization has been added to your cart", "Cart Info", JOptionPane.INFORMATION_MESSAGE);

        
    }//GEN-LAST:event_addJBtnActionPerformed

    private void apartmentTypejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apartmentTypejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apartmentTypejComboBoxActionPerformed

    private void lightFixtureTypejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightFixtureTypejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lightFixtureTypejComboBoxActionPerformed

    private void customerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerTextFieldActionPerformed
        
    }//GEN-LAST:event_customerTextFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void windowjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_windowjComboBoxActionPerformed

    private void spaceHeatingjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spaceHeatingjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spaceHeatingjComboBoxActionPerformed

    private void flooringjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flooringjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flooringjComboBoxActionPerformed

    private void housingComplexTypejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_housingComplexTypejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_housingComplexTypejComboBoxActionPerformed

    private void interiorThemeTypejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interiorThemeTypejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interiorThemeTypejComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJBtn;
    private javax.swing.JComboBox apartmentTypejComboBox;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField customerTextField;
    private javax.swing.JComboBox<String> flooringjComboBox;
    private javax.swing.JComboBox<String> furnitureWoodjComboBox;
    private javax.swing.JComboBox<String> housingComplexTypejComboBox;
    private javax.swing.JComboBox<String> interiorThemeTypejComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> lightFixtureTypejComboBox;
    private javax.swing.JButton nextJButton;
    private javax.swing.JComboBox powerTypejComboBox;
    private javax.swing.JComboBox<String> spaceHeatingjComboBox;
    private javax.swing.JComboBox<String> windowjComboBox;
    // End of variables declaration//GEN-END:variables
}
