/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.customer;

import business.ecosystem.Ecosystem;
import business.enterprise.Enterprise;
import business.organization.CustomerOrganization;
import business.organization.Organization;
import business.useraccount.UserAccount;
import business.workqueue.SelfDesignedWorkRequest;
import business.workqueue.BuyFurnishedApartmentWorkRequest;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harsh
 */
public class CustomerOrdersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerOrdersJPanel
     */
    private JPanel userProcessContainer;
    private CustomerOrganization customerOrganization;
    private UserAccount account;
    private Enterprise enterprise;
    private Ecosystem business;

    public CustomerOrdersJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customerOrganization = (CustomerOrganization) organization;
        this.account = account;
        this.enterprise = enterprise;
        this.business = business;
        customerTextField.setText(account.getUsername());

        populateCustomerTable();
        populateRealtorOrdersTable();
    }

    public void populateCustomerTable() {
        DefaultTableModel model = (DefaultTableModel) customisedOrderJTable.getModel();

        model.setRowCount(0);

        for (WorkRequest wr : account.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof SelfDesignedWorkRequest) {
                Object[] row = new Object[4];
                SelfDesignedWorkRequest sdwr = (SelfDesignedWorkRequest) wr;
                row[0] = sdwr;
                row[1] = sdwr.getRealtorSender() == null ? null : sdwr.getRealtorSender().getEmployee().getName();
                row[2] = sdwr.getRequestDate();
                row[3] = sdwr.getStatus();
                model.addRow(row);
            }

        }
    }

    public void populateRealtorOrdersTable() {
        DefaultTableModel model = (DefaultTableModel) realtorOrdersJTable.getModel();

        model.setRowCount(0);
        {
            for (WorkRequest wr : account.getWorkQueue().getWorkRequestList()) {
                if (wr instanceof BuyFurnishedApartmentWorkRequest) {
                    Object[] row = new Object[4];
                    BuyFurnishedApartmentWorkRequest bfa = (BuyFurnishedApartmentWorkRequest) wr;
                    row[0] = bfa;
                    row[1] = bfa.getSender().getEmployee().getName();
                    row[2] = bfa.getRequestDate();
                    row[3] = bfa.getStatus();
                    model.addRow(row);

                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        customisedOrderJTable = new javax.swing.JTable();
        refreshJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        realtorOrdersJTable = new javax.swing.JTable();
        customerTextField = new javax.swing.JTextField();
        ordersStatusjProgressBar = new javax.swing.JProgressBar();
        checkOrderStatusJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customisedOrderJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "OrderID", "Sender", "RequestDate", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(customisedOrderJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 790, 170));

        refreshJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 660, 170, 40));

        backJButton.setBackground(new java.awt.Color(204, 204, 255));
        backJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, 50));

        realtorOrdersJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "OrderID", "Sender", "RequestDate", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(realtorOrdersJTable);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 720, 800, 170));

        customerTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        customerTextField.setEnabled(false);
        customerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerTextFieldActionPerformed(evt);
            }
        });
        add(customerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 120, 30));

        ordersStatusjProgressBar.setBackground(new java.awt.Color(255, 153, 153));
        ordersStatusjProgressBar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ordersStatusjProgressBar.setStringPainted(true);
        add(ordersStatusjProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 170, -1));

        checkOrderStatusJButton.setBackground(new java.awt.Color(204, 204, 255));
        checkOrderStatusJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        checkOrderStatusJButton.setText("Check Order Status");
        checkOrderStatusJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOrderStatusJButtonActionPerformed(evt);
            }
        });
        add(checkOrderStatusJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Previous and Pending Orders");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel2.setText("Customized Orders");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 171, 40));

        jLabel3.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel3.setText("Furnished Apartment Orders");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 690, 260, 19));

        jLabel4.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel4.setText("Welcome:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateCustomerTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void customerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerTextFieldActionPerformed

    }//GEN-LAST:event_customerTextFieldActionPerformed

    private void checkOrderStatusJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOrderStatusJButtonActionPerformed
        //  progress bar used to check the order status
        int selectedRow = customisedOrderJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select a row", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {
            SelfDesignedWorkRequest sdwr = (SelfDesignedWorkRequest) customisedOrderJTable.getValueAt(selectedRow, 0);
            if (sdwr.getStatus().equalsIgnoreCase("Placed")) {
                ordersStatusjProgressBar.setValue(15); //Set progress of order status
            } else if (sdwr.getStatus().equalsIgnoreCase("Order Final")) {
                ordersStatusjProgressBar.setValue(30);
            } else if (sdwr.getStatus().equalsIgnoreCase("Design Order")) {
                ordersStatusjProgressBar.setValue(50);
            } else if (sdwr.getStatus().equalsIgnoreCase("Pending with Design")) {
                ordersStatusjProgressBar.setValue(65);
            } else if (sdwr.getStatus().equalsIgnoreCase("Design Complete")) {
                ordersStatusjProgressBar.setValue(70);
            } else if (sdwr.getStatus().equalsIgnoreCase("Manufacture Order")) {
                ordersStatusjProgressBar.setValue(80);
                } else if (sdwr.getStatus().equalsIgnoreCase("Pending")) {
                ordersStatusjProgressBar.setValue(90);
                } else if (sdwr.getStatus().equalsIgnoreCase("Constructed")) {
                ordersStatusjProgressBar.setValue(90);
            } else if (sdwr.getStatus().equalsIgnoreCase("Apartment Ready")) {
                ordersStatusjProgressBar.setValue(100);
            }

        }
    }//GEN-LAST:event_checkOrderStatusJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton checkOrderStatusJButton;
    private javax.swing.JTextField customerTextField;
    private javax.swing.JTable customisedOrderJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JProgressBar ordersStatusjProgressBar;
    private javax.swing.JTable realtorOrdersJTable;
    private javax.swing.JButton refreshJButton;
    // End of variables declaration//GEN-END:variables
}
