/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.customer;

import Business.Customer.MasterOrderList;
import Business.Customer.SelfDesignedOrder;
import Business.Customer.SelfDesignedOrderItem;
import business.ecosystem.Ecosystem;
import business.enterprise.CustomerSupportEnterprise;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.CustomerOrganization;
import business.organization.Organization;
import business.organization.RealtorOrganization;
import business.useraccount.UserAccount;
import business.workqueue.SelfDesignedWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harsh
 */
public class ManageOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrderJPanel
     */
    private JPanel userProcessContainer;
    private MasterOrderList mod;
    private SelfDesignedOrder order;
    private CustomerOrganization customerOrganization;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Ecosystem business;

    public ManageOrderJPanel(JPanel userProcessContainer, MasterOrderList mod, SelfDesignedOrder order, Organization organization, UserAccount userAccount, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.mod = mod;
        this.order = order;
        this.customerOrganization = (CustomerOrganization) organization;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.business = business;
        customerTextField.setText(userAccount.getUsername());

        populateTable();
    }

    private void populateTable() {

        DefaultTableModel dtm = (DefaultTableModel) customerCartjTable.getModel();
        dtm.setRowCount(0);

        for (SelfDesignedOrderItem oi : order.getOrderItemList()) {
            Object[] row = new Object[2];
            row[0] = oi;
            row[1] = oi.getCustomizeProduct().getPrice();
            dtm.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerCartjTable = new javax.swing.JTable();
        viewDetailjBtn = new javax.swing.JButton();
        placeOrderjBtn = new javax.swing.JButton();
        deletejButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        customerTextField = new javax.swing.JTextField();
        refreshJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerCartjTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        customerCartjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderItemId", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(customerCartjTable);
        if (customerCartjTable.getColumnModel().getColumnCount() > 0) {
            customerCartjTable.getColumnModel().getColumn(0).setResizable(false);
            customerCartjTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 790, 270));

        viewDetailjBtn.setBackground(new java.awt.Color(204, 204, 255));
        viewDetailjBtn.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        viewDetailjBtn.setText("View Details");
        viewDetailjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailjBtnActionPerformed(evt);
            }
        });
        jPanel1.add(viewDetailjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, 170, 70));

        placeOrderjBtn.setBackground(new java.awt.Color(204, 204, 255));
        placeOrderjBtn.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        placeOrderjBtn.setText("Confirm & Place Order");
        placeOrderjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderjBtnActionPerformed(evt);
            }
        });
        jPanel1.add(placeOrderjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 610, 240, 70));

        deletejButton.setBackground(new java.awt.Color(204, 204, 255));
        deletejButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        deletejButton.setText("Delete");
        deletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deletejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 610, 160, 70));

        backJButton.setBackground(new java.awt.Color(204, 204, 255));
        backJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 120, 50));

        customerTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        customerTextField.setEnabled(false);
        customerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(customerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 120, 30));

        refreshJButton.setBackground(new java.awt.Color(204, 204, 255));
        refreshJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        refreshJButton.setText("Refresh ");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 240, 160, 40));

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Cart");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cart.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel3.setText("Welcome:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, 30));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void customerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerTextFieldActionPerformed

    }//GEN-LAST:event_customerTextFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void viewDetailjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailjBtnActionPerformed
        // TODO add your handling code here:

        int selectedRow = customerCartjTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        SelfDesignedOrderItem oi = (SelfDesignedOrderItem) customerCartjTable.getValueAt(selectedRow, 0);
        ViewOrderDetailsJPanel vjp = new ViewOrderDetailsJPanel(userProcessContainer, oi);
        userProcessContainer.add("VerifyOrderJPanel", vjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewDetailjBtnActionPerformed

    private void deletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = customerCartjTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            SelfDesignedOrderItem oi = (SelfDesignedOrderItem) customerCartjTable.getValueAt(selectedRow, 0);
            order.removeOrderItem(oi);
            populateTable();
        }
    }//GEN-LAST:event_deletejButtonActionPerformed

    private void placeOrderjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderjBtnActionPerformed

        int selectedRow = customerCartjTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        mod.addOrderFromInput(order);

        SelfDesignedWorkRequest cworkrequest = new SelfDesignedWorkRequest();
        cworkrequest.setOrder(order);
        cworkrequest.setStatus("Placed");
        cworkrequest.setCustomerSender(userAccount);
        userAccount.getWorkQueue().getWorkRequestList().add(cworkrequest);

        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof CustomerSupportEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof RealtorOrganization) {

                            organization.getWorkQueue().getWorkRequestList().add(cworkrequest);

                        }
                    }
                }
            }
        }
        JOptionPane.showMessageDialog(null, "Order Placed Successfully", "Information!!", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_placeOrderjBtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTable customerCartjTable;
    private javax.swing.JTextField customerTextField;
    private javax.swing.JButton deletejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton placeOrderjBtn;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton viewDetailjBtn;
    // End of variables declaration//GEN-END:variables
}
