/**
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.customer;

import business.person.Person;
import business.role.CustomerRole;
import business.role.Role;
import business.useraccount.UserAccount;
import business.useraccount.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Harsh
 */
public class SignUpJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignUpJPanel
     */
    JPanel userProcessContainer;
    UserAccountDirectory userAccountDirectory;

    public SignUpJPanel(JPanel userProcessContainer, UserAccountDirectory userAccountDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccountDirectory = userAccountDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        submitJButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        confirmPasswordField = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameTextField.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        usernameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 118, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sign-Up.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 1130, 190));

        jLabel2.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel2.setText("User Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, 20));

        jLabel3.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel3.setText("Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, -1, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Please fill-in all the details below ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 300, 20));

        jLabel5.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel5.setText("Confirm Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, -1, 20));

        submitJButton.setBackground(new java.awt.Color(102, 153, 255));
        submitJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, -1, 40));

        backjButton.setBackground(new java.awt.Color(204, 204, 255));
        backjButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        backjButton.setText("Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 100, 40));

        passwordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 118, 27));

        confirmPasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(confirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 118, 29));
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        String username = usernameTextField.getText();
        char[] password = passwordField.getPassword();
        char[] confirmPassword = confirmPasswordField.getPassword();

        String pwd = String.valueOf(password);
        String confirmPwd = String.valueOf(confirmPassword);
        //form validation
        int check = 1;
        if (username.isEmpty() || pwd.isEmpty() || confirmPwd.isEmpty()) {
            //verificationLabel.setText("Warning! , All fields below are mandatory");
            check = 0;
            JOptionPane.showMessageDialog(null, "All fields in the form are mandatory");
        } else if (!pwd.equals(confirmPwd)) {
            //verificationLabel1.setText("Warning! , Please ensure passwords entered match");
            check = 0;
            JOptionPane.showMessageDialog(null, "Please ensure passwords entered match", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
        if (check == 1) {

            Person emp = new Person();
            emp.setName(usernameTextField.getText());

            UserAccount ua = new UserAccount();
            ua.setEmployee(emp);
            ua.setUsername(username);
            ua.setPassword(pwd);
            Role role = new CustomerRole();

            //verificationLabel1.setText("");
            //verificationLabel.setText("");
            usernameTextField.setText("");
            passwordField.setText("");
            confirmPasswordField.setText("");

            userAccountDirectory.createUserAccount(username, pwd, emp, role);

            JOptionPane.showMessageDialog(null, username + " " + "user created Successfully! ", "Information", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_submitJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
