/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.customer;

import Business.Customer.CustomerApartment;
import Business.Customer.SelfDesignedOrderItem;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Harsh
 */
public class ViewOrderDetailsJPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private SelfDesignedOrderItem orderItem;

    public ViewOrderDetailsJPanel(JPanel userProcessContainer, SelfDesignedOrderItem orderItem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.orderItem = orderItem;
        //  setting the values of the customised car
        CustomerApartment selfDesignedApt = orderItem.getCustomizeProduct();

        apartmentTypejTextField.setText(selfDesignedApt.getApartmentType());
        lightFixtureTypejTextField.setText(selfDesignedApt.getLightFixtureType());
        windowTextField.setText(selfDesignedApt.getWindow());
        furnitureWoodTypejTextField.setText(selfDesignedApt.getFurnitureWoodType());
        housingComplexTypejTextField.setText(selfDesignedApt.getHousingComplexType());
        spaceHeatingjTextField.setText(selfDesignedApt.getSpaceHeating());
        priceTypeJTextField.setText(selfDesignedApt.getInteriorThemeType());
        flooringjTextField.setText(selfDesignedApt.getFlooring());
        powerTypejTextField.setText(selfDesignedApt.getPowerType());
        interiorThemeTypejTextField.setText(selfDesignedApt.getInteriorThemeType());
        priceTypeJTextField.setText(String.valueOf(selfDesignedApt.getPrice()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        priceTypeJTextField = new javax.swing.JTextField();
        apartmentTypejTextField = new javax.swing.JTextField();
        lightFixtureTypejTextField = new javax.swing.JTextField();
        powerTypejTextField = new javax.swing.JTextField();
        windowTextField = new javax.swing.JTextField();
        flooringjTextField = new javax.swing.JTextField();
        spaceHeatingjTextField = new javax.swing.JTextField();
        housingComplexTypejTextField = new javax.swing.JTextField();
        furnitureWoodTypejTextField = new javax.swing.JTextField();
        interiorThemeTypejTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("ORDER DETAIL VERIFICATION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        jLabel2.setText("Apartment Type ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 130, 20));

        jLabel3.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        jLabel3.setText("Power Type ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, 20));

        jLabel4.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        jLabel4.setText("Window Type");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 100, 20));

        jLabel5.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        jLabel5.setText("Flooring Type");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, 20));

        jLabel6.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        jLabel6.setText("Space Heating");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        jLabel7.setText("Housing Complex");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/verify.png"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        jLabel9.setText("Furniture Wood");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, -1, -1));

        jLabel10.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        jLabel10.setText("Price");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, -1, -1));

        jLabel11.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        jLabel11.setText("Light Fixture Type");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        jLabel12.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        jLabel12.setText("Interior Theme");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, -1, -1));

        priceTypeJTextField.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        priceTypeJTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        priceTypeJTextField.setEnabled(false);
        add(priceTypeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 150, -1));

        apartmentTypejTextField.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        apartmentTypejTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        apartmentTypejTextField.setEnabled(false);
        apartmentTypejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apartmentTypejTextFieldActionPerformed(evt);
            }
        });
        add(apartmentTypejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 150, -1));

        lightFixtureTypejTextField.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        lightFixtureTypejTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lightFixtureTypejTextField.setEnabled(false);
        lightFixtureTypejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightFixtureTypejTextFieldActionPerformed(evt);
            }
        });
        add(lightFixtureTypejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 150, -1));

        powerTypejTextField.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        powerTypejTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        powerTypejTextField.setEnabled(false);
        powerTypejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerTypejTextFieldActionPerformed(evt);
            }
        });
        add(powerTypejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 150, -1));

        windowTextField.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        windowTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        windowTextField.setEnabled(false);
        add(windowTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 150, -1));

        flooringjTextField.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        flooringjTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        flooringjTextField.setEnabled(false);
        add(flooringjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 150, -1));

        spaceHeatingjTextField.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        spaceHeatingjTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        spaceHeatingjTextField.setEnabled(false);
        add(spaceHeatingjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 150, -1));

        housingComplexTypejTextField.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        housingComplexTypejTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        housingComplexTypejTextField.setEnabled(false);
        add(housingComplexTypejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 150, -1));

        furnitureWoodTypejTextField.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        furnitureWoodTypejTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        furnitureWoodTypejTextField.setEnabled(false);
        add(furnitureWoodTypejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 150, -1));

        interiorThemeTypejTextField.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 14)); // NOI18N
        interiorThemeTypejTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        interiorThemeTypejTextField.setEnabled(false);
        add(interiorThemeTypejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 150, -1));

        backJButton.setBackground(new java.awt.Color(204, 204, 255));
        backJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void apartmentTypejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apartmentTypejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apartmentTypejTextFieldActionPerformed

    private void powerTypejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerTypejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_powerTypejTextFieldActionPerformed

    private void lightFixtureTypejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightFixtureTypejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lightFixtureTypejTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apartmentTypejTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField flooringjTextField;
    private javax.swing.JTextField furnitureWoodTypejTextField;
    private javax.swing.JTextField housingComplexTypejTextField;
    private javax.swing.JTextField interiorThemeTypejTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lightFixtureTypejTextField;
    private javax.swing.JTextField powerTypejTextField;
    private javax.swing.JTextField priceTypeJTextField;
    private javax.swing.JTextField spaceHeatingjTextField;
    private javax.swing.JTextField windowTextField;
    // End of variables declaration//GEN-END:variables
}
