/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RealtorWorkArea;

import business.ecosystem.Ecosystem;
import business.enterprise.UnitedConstructionEnterprise;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.LayoutOrganization;
import business.organization.Organization;
import business.organization.RealtorOrganization;
import business.useraccount.UserAccount;
import business.workqueue.SelfDesignedWorkRequest;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.util.logging.*;

/**
 *
 * @author Harsh
 */
public class RealtorSelfDesignedOrdersWorkAreaJPanel extends javax.swing.JPanel {

   
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private RealtorOrganization realtorOrganization;
    private UserAccount userAccount;
    private Ecosystem business;
    private final static Logger logr = Logger.getLogger(Logger.GLOBAL_LOGGER_NAME);
    
    public RealtorSelfDesignedOrdersWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.realtorOrganization = (RealtorOrganization) organization;
        this.userAccount = account;
        this.business = business;

        populateCustomerWorkRequestTable();
        
        //add enterprise name to label
        valueLabel.setText(enterprise.getName());
        orgValueLabel.setText(organization.getName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void populateCustomerWorkRequestTable() {
        DefaultTableModel model = (DefaultTableModel) customerWorkRequestJTable.getModel();

        model.setRowCount(0);

        for (WorkRequest wr : realtorOrganization.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof SelfDesignedWorkRequest) {
                Object[] row = new Object[5];
                SelfDesignedWorkRequest sdwr = (SelfDesignedWorkRequest) wr;
                row[0] = sdwr;
                row[1] = sdwr.getCustomerSender() == null ? null : sdwr.getCustomerSender().getEmployee().getName();
                row[2] = sdwr.getRealtorReceiver() == null ? null : sdwr.getRealtorReceiver().getEmployee().getName();
                row[3] = sdwr.getRequestDate();
                row[4] = sdwr.getStatus();
                model.addRow(row);
            }
        }

    }

   

    

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        requestDesignJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        assignJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        customerWorkRequestJTable = new javax.swing.JTable();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        orgValueLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setBackground(new java.awt.Color(204, 204, 255));
        backJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, 40));

        requestDesignJButton.setBackground(new java.awt.Color(204, 204, 255));
        requestDesignJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        requestDesignJButton.setText("Request Architect");
        requestDesignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestDesignJButtonActionPerformed(evt);
            }
        });
        add(requestDesignJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 200, 43));

        refreshJButton.setBackground(new java.awt.Color(204, 204, 255));
        refreshJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 260, 120, 30));

        assignJButton.setBackground(new java.awt.Color(204, 204, 255));
        assignJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        assignJButton.setText("Accept Request");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 200, 43));

        customerWorkRequestJTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        customerWorkRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "OrderID", "Sender", "Receiver", "RequestDate", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(customerWorkRequestJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 890, 120));

        valueLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 170, 26));

        enterpriseLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 130, 30));

        enterpriseLabel1.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Organization:");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 26));

        orgValueLabel.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        orgValueLabel.setText("<value>");
        add(orgValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 190, 26));

        jLabel3.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        jLabel3.setText("Customer Order Requests");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 310, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/orders.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Realtor Staff Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void requestDesignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestDesignJButtonActionPerformed

        int selectedRow = customerWorkRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first ", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        SelfDesignedWorkRequest request = (SelfDesignedWorkRequest) customerWorkRequestJTable.getValueAt(selectedRow, 0);
        request.setStatus("Design Order");
        request.setRealtorSender(userAccount);

        userAccount.getWorkQueue().getWorkRequestList().add(request);
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof UnitedConstructionEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof LayoutOrganization) {
                            organization.getWorkQueue().getWorkRequestList().add(request);

                        }
                    }
                }
            }
        }
        populateCustomerWorkRequestTable();
        JOptionPane.showMessageDialog(null, "Order sent to Architect", "Info", JOptionPane.INFORMATION_MESSAGE);

        logr.info("Request Architect Button clicked");
    }//GEN-LAST:event_requestDesignJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateCustomerWorkRequestTable();
       

    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = customerWorkRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first ", "Warning", JOptionPane.WARNING_MESSAGE);

            return;
        }

        SelfDesignedWorkRequest request = (SelfDesignedWorkRequest) customerWorkRequestJTable.getValueAt(selectedRow, 0);
        request.setRealtorReceiver(userAccount);
        request.setStatus("Order Final");
        populateCustomerWorkRequestTable();


    }//GEN-LAST:event_assignJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTable customerWorkRequestJTable;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel orgValueLabel;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton requestDesignJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
